FROM python:3.9

WORKDIR /app

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Проверка правильного пути к файлу миграций
RUN ls -la . /app/migrations/init.sql

CMD ["sh", "-c", "python -m pytest -xvs"]